#!/usr/bin/env python3
"""
Build a style of the kit into a drop-in bundle.

  python3 tools/build_kit.py                  # super-casual (the default, so the old command still works)
  python3 tools/build_kit.py tactical-dark    # any folder that has <style>/kit/core.css
  python3 tools/build_kit.py --all            # every style in the repo

Output (commit it; games copy this folder as `kit/`):
  <style>/dist/kit.css        core.css + every component CSS, in a safe order
  <style>/dist/kit.js         the runtime — always built from super-casual/kit/sc.js, the one source every style shares
  <style>/dist/assets/        icons + offsets.css + the image prompts
  <style>/dist/registry.json  component + block list for AI agents
  <style>/dist/README.md      how to use the bundle

Every bundle has the same file names, so a game changes style by swapping the folder — no markup changes.

Building super-casual also refreshes templates/pixelfork-game/kit/ (a copy of dist, not committed) so the
template runs. Add --template to build the template from another style instead.
"""
import json, shutil, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASE = "super-casual"                       # owns the runtime and the template
RUNTIME = ROOT / BASE / "kit" / "sc.js"
TEMPLATE_KIT = ROOT / "templates" / "pixelfork-game" / "kit"

# Order matters only where one component restyles another (popup uses buttons, tab bar/alert move bubbles, level sits on progress…)
ORDER = [
    "screen", "button", "icon-button", "counter", "slot", "progress", "title", "stars", "timer", "float",
    "popup", "bubble", "toggle", "slider", "checkbox", "tabs", "tabbar", "tag", "banner", "hint", "toast",
    "row", "loading", "alert", "level", "topbar", "shopcard", "tutorial", "joystick", "actions", "speedometer",
]

def styles():
    return sorted(p.parent.parent.name for p in ROOT.glob("*/kit/core.css"))

def build(style, template):
    KIT, DIST = ROOT / style / "kit", ROOT / style / "dist"
    if not (KIT / "core.css").exists():
        raise SystemExit(f"no such style: {style}  (have: {', '.join(styles())})")
    comps = sorted(p.name for p in (KIT / "components").iterdir() if (p / f"{p.name}.css").exists())
    missing = [c for c in comps if c not in ORDER]
    if missing:
        raise SystemExit(f"Add these components to ORDER in tools/build_kit.py: {missing}")
    unskinned = [c for c in ORDER if c not in comps]       # a style may be partial; say so rather than crash
    order = [c for c in ORDER if c in comps]
    reg = json.loads((KIT / "registry.json").read_text())
    version, title = reg["version"], reg.get("title", f"{style} UI Kit")

    if DIST.exists():
        shutil.rmtree(DIST)
    DIST.mkdir(parents=True)

    parts = [f"/* {title} v{version} — bundle (generated by tools/build_kit.py, do not edit) */\n"]
    parts.append((KIT / "core.css").read_text())            # keeps the font @import at the very top
    for name in order:
        css = (KIT / "components" / name / f"{name}.css").read_text()
        if "@import" in css:
            raise SystemExit(f"{name}.css uses @import — move it to core.css")
        parts.append(f"\n/* ===== {name} ===== */\n{css}")
    (DIST / "kit.css").write_text("".join(parts))

    js = RUNTIME.read_text()
    (DIST / "kit.js").write_text(f"/* {title} v{version} — runtime (copy of sc.js, generated by tools/build_kit.py) */\n{js}")

    shutil.copytree(KIT / "assets", DIST / "assets")
    shutil.copy(KIT / "registry.json", DIST / "registry.json")
    (DIST / "README.md").write_text(f"""# {title} v{version} — bundle

Copy this folder into a game as `kit/` and add two lines:

```html
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover, user-scalable=no">
<link rel="stylesheet" href="kit/kit.css">
<script src="kit/kit.js"></script>
```

Everything is included ({"all " if not unskinned else ""}{len(order)} components). Icons load from `kit/assets/` automatically.
- Components and rules: `registry.json` (full manuals: `{style}/kit/components/<name>/<name>.md` in the kit repo)
- New pictures: `assets/IMAGE-PROMPTS.md`
- A complete wired game to start from: `templates/pixelfork-game/`

Generated by `tools/build_kit.py` — edit the kit source in `{style}/kit/`, then rebuild.
""")

    if template and TEMPLATE_KIT.parent.exists():
        if TEMPLATE_KIT.exists():
            shutil.rmtree(TEMPLATE_KIT)
        shutil.copytree(DIST, TEMPLATE_KIT)

    size = (DIST / "kit.css").stat().st_size // 1024
    if unskinned:
        print(f"  {style}: not skinned yet, left out of the bundle: {', '.join(unskinned)}")
    print(f"built {style} v{version}: kit.css {size} KB, kit.js {(DIST / 'kit.js').stat().st_size // 1024} KB, "
          f"{len(list((DIST / 'assets').glob('*.png')))} icons → {DIST.relative_to(ROOT)}")

def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    todo = styles() if "--all" in sys.argv else (args or [BASE])
    for style in todo:
        build(style, template=(style == BASE and "--template" not in sys.argv) or ("--template" in sys.argv and style == todo[-1]))

if __name__ == "__main__":
    main()
