#!/usr/bin/env python3
"""
Build the Super Casual kit into a drop-in bundle.

  python3 tools/build_kit.py

Output (commit it; games copy this folder as `kit/`):
  super-casual/dist/kit.css        core.css + every component CSS, in a safe order
  super-casual/dist/kit.js         the runtime (sc.js)
  super-casual/dist/assets/        icons + offsets.css + IMAGE-PROMPTS.md
  super-casual/dist/registry.json  component + block list for AI agents
  super-casual/dist/README.md      how to use the bundle

Also refreshes templates/pixelfork-game/kit/ (a copy of dist, not committed) so the template runs.
"""
import json, re, shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
KIT = ROOT / "super-casual" / "kit"
DIST = ROOT / "super-casual" / "dist"
TEMPLATE_KIT = ROOT / "templates" / "pixelfork-game" / "kit"

# Order matters only where one component restyles another (popup uses buttons, tab bar/alert move bubbles, level sits on progress…)
ORDER = [
    "screen", "button", "icon-button", "counter", "slot", "progress", "title", "stars", "timer", "float",
    "popup", "bubble", "toggle", "slider", "checkbox", "tabs", "tabbar", "tag", "banner", "hint", "toast",
    "row", "loading", "alert", "level", "topbar", "shopcard", "tutorial", "joystick", "actions",
]

def main():
    comps = sorted(p.name for p in (KIT / "components").iterdir() if (p / f"{p.name}.css").exists())
    missing = [c for c in comps if c not in ORDER]
    if missing:
        raise SystemExit(f"Add these components to ORDER in tools/build_kit.py: {missing}")
    version = json.loads((KIT / "registry.json").read_text())["version"]

    if DIST.exists():
        shutil.rmtree(DIST)
    DIST.mkdir(parents=True)

    parts = [f"/* Super Casual UI Kit v{version} — bundle (generated by tools/build_kit.py, do not edit) */\n"]
    parts.append((KIT / "core.css").read_text())            # keeps the font @import at the very top
    for name in ORDER:
        css = (KIT / "components" / name / f"{name}.css").read_text()
        if "@import" in css:
            raise SystemExit(f"{name}.css uses @import — move it to core.css")
        parts.append(f"\n/* ===== {name} ===== */\n{css}")
    (DIST / "kit.css").write_text("".join(parts))

    js = (KIT / "sc.js").read_text()
    (DIST / "kit.js").write_text(f"/* Super Casual UI Kit v{version} — runtime (copy of sc.js, generated by tools/build_kit.py) */\n{js}")

    shutil.copytree(KIT / "assets", DIST / "assets")
    shutil.copy(KIT / "registry.json", DIST / "registry.json")
    (DIST / "README.md").write_text(f"""# Super Casual UI Kit v{version} — bundle

Copy this folder into a game as `kit/` and add two lines:

```html
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover, user-scalable=no">
<link rel="stylesheet" href="kit/kit.css">
<script src="kit/kit.js"></script>
```

Everything is included (all {len(ORDER)} components). Icons load from `kit/assets/` automatically.
- Components and rules: `registry.json` (full manuals: `super-casual/kit/components/<name>/<name>.md` in the kit repo)
- New pictures: `assets/IMAGE-PROMPTS.md`
- A complete wired game to start from: `templates/pixelfork-game/`

Generated by `tools/build_kit.py` — edit the kit source in `super-casual/kit/`, then rebuild.
""")

    if TEMPLATE_KIT.parent.exists():
        if TEMPLATE_KIT.exists():
            shutil.rmtree(TEMPLATE_KIT)
        shutil.copytree(DIST, TEMPLATE_KIT)

    size = (DIST / "kit.css").stat().st_size // 1024
    print(f"built v{version}: kit.css {size} KB, kit.js {(DIST / 'kit.js').stat().st_size // 1024} KB, "
          f"{len(list((DIST / 'assets').glob('*.png')))} icons → {DIST.relative_to(ROOT)}")

if __name__ == "__main__":
    main()
