"""
Find a style's single-colour white glyph icons and let a theme recolour them.

  python3 tools/glyph_list.py tactical-dark

White glyphs (pause, home, settings…) disappear on a light theme. An <img> cannot be recoloured with `color`,
but a filter can: this writes one rule into the style's core.css, between markers, that applies
`filter:var(--sc-glyph-filter)` to exactly those icons — painted colour icons (coin, gem, medkit) are left alone.
A dark theme leaves the token at `none`; a light theme sets `brightness(0)` (black) or `brightness(.25)`.
Run again after adding icons.
"""
import pathlib, re, sys
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
style = sys.argv[1]
KIT = ROOT / style / 'kit'
glyphs = []
for f in sorted((KIT / 'assets').glob('*.png')):
    im = Image.open(f).convert('RGBA'); im.thumbnail((64, 64))
    px = [p for p in (im.get_flattened_data() if hasattr(im, "get_flattened_data") else im.getdata()) if p[3] > 128]
    if not px: continue
    grey_light = sum(1 for r, g, b, a in px if max(r, g, b) - min(r, g, b) < 28 and min(r, g, b) > 150)
    if grey_light / len(px) > .9: glyphs.append(f.stem)

sel = ',\n'.join(f'img[src*="assets/"][src$="/{n}.png"]' for n in glyphs)
# :where() keeps both rules at the weight of their first part, so no component rule ever ties with them.
# A button is filled with its accent and carries its own label colour, so its glyph follows the label, not the page.
block = (f'/* glyphs:start — generated by tools/glyph_list.py, do not edit */\n'
         f':where({sel}) {{ filter:var(--sc-glyph-filter); }}\n'
         f'.sc-button > :where({sel}),\n:is(.sc-icon-button:not([data-variant]), .sc-icon-button[data-variant="glossy"]) > :where({sel}) {{ filter:var(--sc-glyph-on-button); }}\n/* glyphs:end */\n')
core = KIT / 'core.css'; t = core.read_text()
t = re.sub(r'/\* glyphs:start.*?glyphs:end \*/\n', '', t, flags=re.S).rstrip('\n') + '\n\n' + block
core.write_text(t)
print(f'{style}: {len(glyphs)} glyph icons of {len(list((KIT / "assets").glob("*.png")))}: {" ".join(glyphs)}')
