"""
Give a style folder the same structure as super-casual/kit.

The two styles share the runtime and the docs renderer, and every component keeps the same class names and
attributes, so the docs PAGES work unchanged — they load "../core.css" and "../components/x/x.css", which
resolve to whichever style they sit in. This script copies those shared pieces into a style and writes a
docs.js whose sidebar lists only the components that style has actually skinned.

Everything it writes is generated: edit the source in super-casual/kit, then run this again.

  python3 tools/sync_style.py tactical-dark "Tactical Dark" 0.2.0
"""
import json, pathlib, re, shutil, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / 'super-casual' / 'kit'
style, title = sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else sys.argv[1]
DST = ROOT / style / 'kit'
if not DST.exists():
    raise SystemExit(f'no such style: {DST}')

VERSION = sys.argv[3] if len(sys.argv) > 3 else '0.2.0'      # python3 tools/sync_style.py <style> "<Title>" [version]
built = sorted(p.name for p in (DST / 'components').iterdir() if (p / f'{p.name}.css').exists())
print(f'{style}: {len(built)} components skinned — {", ".join(built)}')

GEN = f'/* Generated by tools/sync_style.py from super-casual/kit — do not edit here. */\n'

# 1. the runtime, byte for byte
shutil.copyfile(SRC / 'sc.js', DST / 'sc.js')
(DST / 'sc.js').write_text(GEN + (DST / 'sc.js').read_text())

# 2. the docs renderer + stylesheet
(DST / 'docs').mkdir(exist_ok=True)
shutil.copyfile(SRC / 'docs' / 'docs.css', DST / 'docs' / 'docs.css')

docs_js = (SRC / 'docs' / 'docs.js').read_text()
# keep every component in the sidebar, but only link the ones this style has (docs.js renders the rest as "soon")
def keep(m):
    label, href = m.group(1), m.group(2)
    return f"['{label}', '{href}']" if href.replace('.html', '') in built else f"['{label}', null]"
nav = re.search(r"\{ group: 'Components', items: \[(.*?)\] \}", docs_js, re.S)
items = re.sub(r"\['([^']+)', '([^']+\.html)'\]", keep, nav.group(1))
items = items.rstrip().rstrip(',') + ", ['Icons', 'icons.html']"        # every style lists its own icons
docs_js = docs_js[:nav.start(1)] + items + docs_js[nav.end(1):]
docs_js = docs_js.replace('Super Casual UI Kit', f'{title} UI Kit')
docs_js = re.sub(r'v\d+\.\d+ · for mobile web games', f'v{VERSION} · {len(built)} of 30 components', docs_js)
# blocks and examples: link the ones this style has, grey out the rest rather than linking into the other style
def keep_page(m):
    return m.group(0) if (DST / m.group(2) / m.group(3)).exists() else f"['{m.group(1)}', null]"
docs_js = re.sub(r"\['([^']+)', '\.\./(blocks|examples)/([^']+)'\]", keep_page, docs_js)
(DST / 'docs' / 'docs.js').write_text(GEN.replace('/*', '/*').rstrip() + '\n' + docs_js)

# 2b. the blocks device preview (docs helper) and the blocks README, once the style has blocks
if (DST / 'blocks').exists() and any((DST / 'blocks').glob('*.html')):
    shutil.copyfile(SRC / 'blocks' / 'preview.js', DST / 'blocks' / 'preview.js')
    for name in ('preview.html', 'README.md'):
        (DST / 'blocks' / name).write_text((SRC / 'blocks' / name).read_text()
            .replace('Super Casual UI Kit', f'{title} UI Kit').replace('#1f2d4b', '#070B16'))

# 3. one docs page per skinned component, plus the prose pages
pages = [f'{c}.html' for c in built if (SRC / 'docs' / f'{c}.html').exists()]
for name in pages + ['introduction.html', 'installation.html', 'images.html']:
    src = SRC / 'docs' / name
    if not src.exists():
        continue
    (DST / 'docs' / name).write_text(src.read_text().replace('Super Casual UI Kit', f'{title} UI Kit'))

# 4. the AI manual next to each component
for c in built:
    md = SRC / 'components' / c / f'{c}.md'
    if md.exists():
        (DST / 'components' / c / f'{c}.md').write_text(
            md.read_text().replace('Super Casual UI Kit', f'{title} UI Kit') +
            f'\n\n> Style: **{title}**. Same markup, attributes and events as every other style of this kit —\n'
            f'> only the CSS differs. See ../../STYLE.md.\n')

# 4b. the Icons page: one tile per file in assets/, so the whole set can be checked at a glance
icons = sorted(p.stem for p in (DST / 'assets').glob('*.png'))
tiles = '\n'.join(
    f'<figure class="icon"><img src="../assets/{n}.png" alt="" loading="lazy"><figcaption>{n}</figcaption></figure>'
    for n in icons)
(DST / 'docs' / 'icons.html').write_text(f"""<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Icons — {title} UI Kit</title>
<!-- Generated by tools/sync_style.py from the files in ../assets — do not edit by hand. -->
<link rel="stylesheet" href="../core.css">
<link rel="stylesheet" href="../assets/offsets.css">
<link rel="stylesheet" href="docs.css">
<script src="../sc.js" data-assets="../assets/"></script>
<script src="docs.js"></script>
<style>
  .icon-grid {{ display:grid; grid-template-columns:repeat(auto-fill, minmax(104px, 1fr)); gap:10px; margin:0 0 28px; }}
  .icon {{ margin:0; padding:14px 6px 10px; border-radius:10px; background:#0e1628; text-align:center; }}
  .icon img {{ width:46px; height:46px; object-fit:contain; display:block; margin:0 auto 9px; }}
  .icon figcaption {{ font:12px ui-monospace, monospace; color:#8ca3c7; word-break:break-all; }}
</style></head>
<body>
<script>
SCDocs.article({{
  title: 'Icons',
  lead: '{len(icons)} icons in this style. Use one by name with <code class="inline">data-icon</code>, or pass a path or a web address instead. <code class="inline">SC.setImage</code> swaps one for the whole game.',
  body: `<div class="icon-grid">{tiles}</div>
    <h2>Adding to this set</h2>
    <p class="desc">Generate on one sheet so the icons match each other, then cut, clean and normalise:</p>
    <pre data-code>python3 tools/gen_image.py --prompt-file sheet.txt _staging/sheet.png
python3 tools/crop_sheet.py _staging/sheet.png 4 4 {style}/kit/assets name1 name2 …
python3 tools/normalize_icons.py {style}/kit/assets
python3 tools/icon_offsets.py {style}/kit/assets {style}/kit/assets/offsets.css</pre>`,
}});
</script>
</body></html>
""")

# 5. a registry listing what this style actually has
reg = json.loads((SRC / 'registry.json').read_text())
reg['name'] = f'{style}-ui-kit'
reg['title'] = f'{title} UI Kit'
reg['version'] = VERSION
reg['items'] = [i for i in reg['items'] if i['name'] in built]
reg.pop('cdn', None)
reg['icons'] = {**reg.get('icons', {}), 'names': sorted(p.stem for p in (DST / 'assets').glob('*.png'))}
(DST / 'registry.json').write_text(json.dumps(reg, indent=2) + '\n')

print(f'  docs pages: {len(pages)} + 3 prose · manuals: {len(built)} · registry: {len(reg["items"])} items')
print(f'  open http://localhost:8767/{style}/kit/docs/introduction.html')
